### PR TITLE
Compile with GHC 8.10.1

### PR DESCRIPTION
**Pull request by dbeacham**
* No implicit parameters to forall
* UndecidableInstances needed for some type family instances

### CODE REVIEW

**Comment by dbeacham** [comment]
Somewhat ugly with the CPP, there is a suggestion in the [migration notes](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/8.10#implicit-kind-variable-changes) to consider

```haskell
#if __GLASGOW_HASKELL__ >= 810
# define KVS(kvs) kvs
#else
# define KVS(kvs)
#endif

rpureConstrained :: forall KVS(u) c (f :: u -> *) proxy ts
```

rather than explicit `CPP` around each type signature. Could also change the test to `800` rather than `810` if there was a correspsonding version bump as it's a breaking change for `TypeApplications`.

Tested against `HEAD` of `doctest` as hackage not currently updated to support `8.10`.

**Comment by acowley** [comment]
Thank you! Does explicitly quantifying the kinds not work on earlier GHC? If it's the type application breakage that we're worried about, could we do something like is done [here](https://github.com/VinylRecords/Vinyl/blob/master/Data/Vinyl/Lens.hs#L122) to provide a short name whose definition includes the uninteresting type application arguments?

**Comment by dbeacham** [comment]
I don't think this will work.

From my understanding/playing around with the ordering in the `forall` - you need to quantify the kind variable before any of its dependencies. So there'll always be a kind variable appearing first in the signature/type application.

You can make the interface standard across all GHC >= 8.0 by explicitly quantifying the kinds - 8.0, 8.2, 8.4 would need `TypeInType` turned on - but I don't think you can maintain backward compatibility with `TypeApplications`.

**Comment by dbeacham** [comment]
1. Added missing CPP for `StandaloneTypeSignatures` in `tests/Intros.lhs` due to change in `singletons:genSingletons` in GHC 8.10

2. Having thought about this a bit more rather than just making it compile for 8.10 I've made the API consistent across all GHC versions - i.e. explicit kind quantification - with CPP to turn on appropriate PRAGMAs and imports across different GHCs.

**Comment by acowley** [comment]
Sorry this is taking so long. It seems like a lot of dependencies aren't yet ready for 8.10. I made some progress in provisioning a build and test environment, but I'm not there yet.

**Comment by dbeacham** [comment]
No problem - I had to point some packages explicitly at gihub source when building/testing as the necessary changes hadn't been uploaded to hackage yet.

But makes sense to wait for ecosystem to catch up first for testing etc. to be reliable.

**Comment by acowley** [comment]
These commits have been merged, and a new release pushed to hackage. Thank you for the help!

**Pull request closed without merging**
