### PR TITLE
FieldRec and HList fields access performace test.

### PR DESCRIPTION
**Pull request by schernichkin**
#108

### CODE REVIEW

**Comment by acowley** [comment]
Take a look at [this branch](https://github.com/VinylRecords/Vinyl/tree/AccessorsBench) and see if it makes sense to you. I will write up some notes to be added to the README. Maybe we can extract a single nice graph to include as a visual aid.

**Comment by schernichkin** [comment]
Nice trick) On my system (GHC 8.2.2) it still shows performance degradation for FieldRec. FieldRec Storable seems to run in constant time.

**Comment by schernichkin** [comment]
I't seems hspec-2.6.0 out of vinyl's bounds: [link](https://github.com/commercialhaskell/stackage/pull/4139). I've checked it with hspec-2.6.0 it works fine.

**Comment by acowley** [comment]
Thank you!

**Pull request merged**
